version: '3.1'
networks:
  vidivadev:
    name: vidivadev
    external: true

services:
  dns-server:
    image: xdung24/dns-server
    container_name: dns-server
    restart: always
    environment:
      - HTTP_USER=changeme
      - HTTP_PASS=changeme
      - TZ=Asia/Ho_Chi_Minh
    ports:
      # - 8080:8080/tcp  # uncomment to use web ui
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - ./dns-server/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - vidivadev

  php-myadmin:
    image: xdung24/php-myadmin
    container_name: php-myadmin
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=500M
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    ports:
      - 8081:80
    networks:
      - vidivadev
    volumes:
      - /sessions
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./phpmyadmin/php.ini:/usr/local/etc/php/php.ini
      - /var/run/mysqld/mysqld.sock:/tmp/mysqld.sock

  redis-ui:
    image: xdung24/redis-ui
    container_name: redis-ui
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 8082:7843
    volumes:
      - ./redis-ui/settings:/settings
    networks:
      - vidivadev

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 8083:80
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PGADMIN_DEFAULT_EMAIL=pg@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      - vidivadev

  mongodb-gui:
    image: samueltallet/mongodb-php-gui
    container_name: mongodb-gui
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    ports:
      - 8084:5000
    networks:
      - vidivadev